### ISSUE TITLE
minor FYI chrome app to be depreciated late 2017

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/js-ajax-ajax-and-callbacks-readme#1]
Chrome plugin to be depreciated in late 2017.    https://www.getpostman.com/apps

Chrome Apps will be deprecated in late 2017. We recommend users download a Mac, Windows, or Linux version, for best performance and support. More info: 
http://blog.getpostman.com/2016/08/23/using-the-postman-chrome-app-implications-from-the-recent-google-announcement/?_ga=2.178408356.1487971280.1508461478-1022766942.1508461478

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @smithWEBtek.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
