### ISSUE TITLE
'error' variable is an object, not a string describing the error

### ISSUE THREAD

**Issue by dj-sf** [learn-co-curriculum/js-ajax-ajax-and-callbacks-readme#2]
```
$.get("this_doesnt_exist.html", function(data) {
  // This will not be called because the .html file request doesn't exist
  doSomethingGood();
}).fail(function(error) {
  // This is called when an error occurs
  console.log('Something went wrong: ' + error);
});
```

In the above code snippet, the ```error``` variable is an object, not a string.  The way it currently is in the readme, the string printed to the console actually says ```Something went wrong: [object Object]``` which is not the desired behavior.  I recommend changing the ```error``` variable in the console.log line to ```error.statusText```.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
Thanks for your contribution 💙
