### ISSUE TITLE
Postman chrome extension, says it's being deprecated

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-ajax-ajax-and-callbacks-readme#4]
Postman Installation
Visit https://www.getpostman.com and install the Chrome extension.
Once you have it installed, open Postman from the Chrome Apps menu.
Skip the signup and go straight to the app.

--THIS section should be changed, to get the web app?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @MiriamPeskowitz.

We have updated the materials, removed references to the Postman Chrome extension and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
